// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DateRangePicker: typeof import('./../src/components/DateRangePicker/index.vue')['default']
    TimeRangePicker: typeof import('./../src/components/TimeRangePicker/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
  }
}

export {}
